name : Deploy to github Pages

on:
  push:
    branches:
      - main

permissions:
  content: write
  Pages: write
  id-token: write

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/Checkout@v4
      
      - name: setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with :
          path: ./

      - name: Deploy to Github Pages 